version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    platform: linux/amd64
    restart: always
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    platform: linux/amd64
    restart: always
    ports:
      - "9090:80"
    environment:
      PMA_HOST: ${PMA_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  backend:
    build: ./backend
    container_name: backend_container
    platform: linux/amd64
    restart: always
    command: >
      sh -c "npm install && npm run dev"
    volumes:
      - ./backend:/srv/app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    env_file:
      - .env

  vue-web:
    container_name: frontend_container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: >
      sh -c "npm install && npm run dev"
    volumes:
      - ./frontend:/srv/app
    ports:
      - "80:5173"
    environment:
      - NODE_ENV=development
    init: true
    stop_grace_period: 1s
    networks:
      - network

volumes:
  mysql_data:

networks:
  network:
    driver: bridge

